FROM debian:jessie

MAINTAINER Michael Pavlista <pavlista@rtsoft.cz>

# Nastavení Debianu
ENV DEBIAN_FRONTEND=noninteractive

# Ošetření chyby: invoke-rc.d: policy-rc.d denied execution of start.
RUN sed -i "s/^exit 101$/exit 0/" /usr/sbin/policy-rc.d

# Základní repozitář pro Debian Jessie
RUN echo "deb http://ftp.cz.debian.org/debian jessie main" > /etc/apt/sources.list.d/jessie.list

# Aktualizace definice balíčků a instalace základních balíčků
RUN apt-get update && \
    apt-get install -y --no-install-recommends dialog apt-utils git mc htop nmap wget curl \
    apt-transport-https ca-certificates openssh-client screen

# Instalace a nastavení Apache
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid

RUN apt-get update && apt-get install -y apache2 && \
    a2enmod include && \
    a2enmod rewrite && \
    a2enmod proxy_fcgi && \
    rm /etc/apache2/sites-enabled/000-default.conf

COPY ./files/apache/apache2.conf /etc/apache2/

# nastavení, aby apache proces vytvářel soubory s právy RW-RW-R--, takže když se uživatel přidá do stejné skupiny, má právo manipulovat se soubory vytvořenými apache
RUN echo "umask 002" >>  /etc/apache2/envvars

# Instalace supervisord
RUN apt-get update && apt-get install -y supervisor
RUN groupadd supervisor
RUN usermod -a root -G supervisor
COPY ./files/supervisor/supervisord.conf /etc/supervisor/

# Instalace a nastavení PHP (7.2)
# Pro běžný provoz budeme používat PHP balíčky z repozitáře: https://deb.sury.org
RUN apt-get update && apt-get install -y apt-transport-https lsb-release ca-certificates && \
    wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg && \
    sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list' && \
    apt-get update

RUN apt-get update && apt-get install -y --no-install-recommends php7.2 php7.2-cli libapache2-mod-php7.2 \
    php7.2-curl \
    php7.2-gd \
    php7.2-imagick \
    php7.2-imap \
    php7.2-intl \
    php7.2-json \
    php7.2-mbstring \
    php7.2-mysql \
    php7.2-pdo \
    php7.2-redis \
    php7.2-soap \
    php7.2-xml \
    php7.2-bcmath \
    php7.2-zip

COPY ./files/php/php.ini /etc/php/7.2/apache2/
COPY ./files/php/php.ini /etc/php/7.2/cli/

# korekce práv k adresáři, kam si php ukládá session
RUN chown www-data:www-data /var/lib/php/sessions

# Instalace Composeru
ENV COMPOSER_ALLOW_SUPERUSER 1
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer config http-basic.composer.rtsoft.cz satis Z6ueE7wyNZYnV$^rLRVvLUW_C -g

# Instalace Presstissima které zajišťuje pararelní stahování balíčku přes composer (něco jako Yarn)
RUN composer global require "hirak/prestissimo:^0.3"

# Instalace RabbitMQ
RUN echo 'deb http://www.rabbitmq.com/debian/ testing main' | tee /etc/apt/sources.list.d/rabbitmq.list
RUN wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | apt-key add -
RUN apt-get update && apt-get install -y rabbitmq-server php5.6-bcmath
RUN rabbitmq-plugins enable rabbitmq_management

# Pročištění souborů a cache dockerimage
RUN apt-get clean -y && apt-get autoclean -y && apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/* /var/lib/log/* /tmp/* /var/tmp/*

# Otevření potřebných portů
EXPOSE 80
EXPOSE 443
EXPOSE 9001
EXPOSE 15672

# Nastavení mc
COPY ./files/root/.config /root/.config/

# Skripty v bin
COPY ./files/bin/* /usr/local/bin/
RUN chmod +x /usr/local/bin/*

# Nastaveni domovskeho adresare
WORKDIR /var/www/html

# Nastartování služeb při zapnutí konteineru
RUN sed -i 's/\r$//' /usr/local/bin/container.start.sh
CMD /usr/local/bin/container.start.sh
